### ISSUE TITLE
[QUESTION] Short sentences in en 

### ISSUE THREAD

**Issue by loretoparisi** [MighTguY/customized-symspell#24]
Hello, I have found this case that seems strange for the input string `"I am the begt spell cherken!"`:

```java
int maxEd = 2;
suggestionItems = symSpellCheck.lookupCompound("I am the begt spell cherken!", maxEd);
    for (SuggestionItem elem : suggestionItems) {
      System.out.println("compound : " + elem.getTerm().trim());
    }
```

I'm getting `compound : a am the best spell cher ken`

My setup is the default one:
```java
    SpellCheckSettings spellCheckSettings = SpellCheckSettings.builder().countThreshold(1).deletionWeight(1f)
        .insertionWeight(1f).replaceWeight(1f).maxEditDistance(2).transpositionWeight(1f).topK(5).prefixLength(10)
        .verbosity(Verbosity.ALL).build();

    dataHolder = new InMemoryDataHolder(spellCheckSettings, new Murmur3HashFunction());

// weighted Damerau-Levenshtein
    weightedDamerauLevenshteinDistance = new WeightedDamerauLevenshteinDistance(spellCheckSettings.getDeletionWeight(),
        spellCheckSettings.getInsertionWeight(), spellCheckSettings.getReplaceWeight(),
        spellCheckSettings.getTranspositionWeight(), null);

    symSpellCheck = new SymSpellCheck(dataHolder, weightedDamerauLevenshteinDistance, spellCheckSettings);
```

**Comment by MighTguY** [comment]
_I_ to _a_ conversion is happening due to the casing issue, which I have fixed in the PR.
Also for _cherken_ to _'cher ken'_  is happening due to lookup compound algo.
Currently, the spell correction works mainly on the term frequency of the words, and it mainly doesn't include the previous word meaningful context. the top word suggested from the symspell at the time of lookup is itself not _checker_, it's _chicken_ so hence it's giving such output, 

I am currently working to add noisy channel with the current algo for spell checker to add much meaningful context.

**Comment by loretoparisi** [comment]
@MighTguY thank you. I will try to build the latest PR thank. 
Regarding context based spelling, I was discussing about it with @wolfgarbe in https://github.com/wolfgarbe/SymSpell/issues/61

where he suggests this approach: https://blog.usejournal.com/a-simple-spell-checker-built-from-word-vectors-9f28452b6f26?gi=5df44b8031b6

Jupyter code with common mistakes here: https://github.com/er214/spellchecker

Other interesting **ngram** based approach may be used in

- [LanguageTool](https://github.com/languagetool-org/languagetool), Java, http://wiki.languagetool.org/tips-and-tricks#toc2
- [JamSpell](https://github.com/bakwc/JamSpell), C++

**Comment by MighTguY** [comment]
Hi, @loretoparisi  The fix has been done, for the lower case. I have also added the Solr Plugin code to use the symspell lib.
